/**
 * Legacy inventory service facade.
 */
export {
  InventoryRestockError,
  auditInventoryIntegrity,
  fetchProductMovements,
  fetchMerchantInventorySummary,
  fetchGlobalMovements,
  fetchInventoryForecast,
  fetchAbcAnalysis,
  lookupProductByBarcode,
  fetchWarehouses,
  fetchSuppliers,
  fetchPurchaseOrders,
  fetchPurchaseOrderLines,
  fetchOpenCycleCounts,
  fetchCycleCountLines,
  fetchWarehouseStock,
  type InventoryMovementRow,
  type InventoryIntegritySummary,
  type InventoryIntegrityResult,
  type MerchantInventorySummary,
  type InventoryForecastItem,
  type AbcAnalysisItem,
  type WarehouseRow,
  type SupplierRow,
  type PurchaseOrderRow,
  type PurchaseOrderLineRow,
  type CycleCountRow,
  type CycleCountLineRow,
} from '@/services/read/inventory/inventoryReadService';

export {
  restockProduct,
  applyStockQuantityPatch,
  batchRestockProducts,
  batchRestockWithSuggestions,
  ensureDefaultWarehouse,
  transferWarehouseStock,
  createSupplier,
  createPurchaseOrder,
  receivePurchaseOrderLine,
  startCycleCount,
  submitCycleCountLine,
  completeCycleCount,
  createWarehouse,
  type BatchRestockItem,
  type BatchRestockResult,
} from '@/services/write/inventory/inventoryWriteService';
