/**
 * Merchant product & category layer — canonical import for catalog CRUD.
 * Implementation: `data/dummyData.ts` (migration to explicit ownerId in progress).
 */
export {
  checkSupabaseConnection,
  listProducts,
  getProductById as getProductByIdFromDb,
  createProduct,
  updateProduct as updateProductInDb,
  deleteProduct as deleteProductFromDb,
  type ProductsCrudResult,
  type ListProductsOptions,
} from '@/services/productsCrudService';

export {
  setCurrentOwner,
  setCurrentStore,
  getCurrentStoreId,
  getCategories,
  getCategoriesSync,
  PRODUCTS_PAGE_SIZE,
  loadProductsPage,
  loadProducts,
  loadAllMerchantProducts,
  getProductsSync,
  products,
  reloadProducts,
  invalidateCache,
  invalidateOwnerCache,
  invalidateProducts,
  invalidateCategories,
  appendCachedProduct,
  patchCachedProduct,
  removeCachedProduct,
  syncMerchantProductCatalog,
  patchMerchantStockInCache,
  addProduct,
  updateProduct,
  setProductLifecycle,
  publishProduct,
  deleteProduct,
  getProductsByCategory,
  getProductById,
  fetchProductById,
  addCategory,
  updateCategory,
  deleteCategory,
  type ProductsPageResult,
} from '@/data/dummyData';
