GRANT ALL ON SCHEMA public TO sandbox_exec;
GRANT ALL ON SCHEMA auth TO sandbox_exec;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sandbox_exec;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sandbox_exec;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sandbox_exec;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO sandbox_exec;