// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aodioegeoymugdjtaabs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZGlvZWdlb3ltdWdkanRhYWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTcxMzksImV4cCI6MjA2NjY3MzEzOX0.XJh_anoOutO_Cff_euixDrn8nNa6bq-EUIXYhU48UaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);