// This file is automatically generated. Do not edit it directly.
export { getSupabaseClient, resetSupabaseClient } from '@/lib/disasterRecovery/supabaseClient';

import { getSupabaseClient } from '@/lib/disasterRecovery/supabaseClient';

/** Resilient Supabase client (primary / failover). */
export const supabase = getSupabaseClient();
// Prefer generated schema from `npm run db:types` (merged in types.ts).

